from typing import override

def get_integer_input(
    prompt: str,
    error_msg: str = "Value must be a valid integer.",
    error_msg_min: str = "Value is too low.",
    error_msg_max: str = "Value is too high.",
    min_input: int = 0,
    max_input: int = 1000,
) -> int: ...

class Card:
    SUITS: list[str]
    RANKS: list[str]
    RED_SUITS: list[str]
    BLUE_SUITS: list[str]
    instance_count: int
    suit: str
    rank: str
    card_str: str
    def __init__(self, rank: str, suit: str, is_temp: bool = False) -> None: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __hash__(self) -> int: ...
    def get_plain_string(self) -> str: ...

def string_cleaner(input_str: str) -> list[Card]: ...

class Deck:
    instance_count: int
    INSTANCE_LIST: list["Deck"]
    id: str
    deck: list[Card]
    def __init__(self, idd: str = "def") -> None: ...
    def shuffle(self, steps: int = 5) -> None: ...
    def take_cards(
        self, count: int, random_take: bool = False, shuffle_after: bool = False
    ) -> list[Card]: ...
    def put_cards(self, cards: list[Card], shuffle_after: bool = True) -> None: ...
    def search_card_loc_deck(
        self, search_target: list[Card]
    ) -> dict[Card, int | None]: ...

def encrypt_hand(
    input_list: list[Card], random_key: bool = True, given_key: int = 0
) -> tuple[list[str], int]: ...

class Hand:
    instance_count: int
    INSTANCE_LIST: list["Hand"]
    id_hand: int
    type_hand: str
    hand_c: list[Card]
    is_hidden: bool
    def __init__(
        self, idh: int, type_h: str = "player", is_hidden: bool = False
    ) -> None: ...
    def destroy(self) -> list[Card]: ...
    def shuffle(self, steps: int = 5) -> None: ...
    def take_cards_exact(self, cards: list[Card]) -> list[Card]: ...
    def take_cards(
        self, count: int, random_take: bool = False, shuffle_after: bool = False
    ) -> list[Card]: ...
    def put_cards(self, cards: list[Card]) -> None: ...
    def search_card_loc_hand(
        self, search_target: list[Card]
    ) -> dict[Card, int | None]: ...

def reset_game() -> None: ...
def clear_screen() -> None: ...
def get_hands_from_input(prompt: str, hands_dict: dict[str, Hand]) -> list[Hand]: ...
def handle_drawn_destination(cards: list[Card], hands_dict: dict[str, Hand]) -> None: ...

MENU: str

def main_loop() -> None: ...
