def encrypt(input_string: str, key: int, alphabet: str | None = None) -> str: ...


def decrypt(input_string: str, key: int, alphabet: str | None = None) -> str: ...


def brute_force(input_string: str, alphabet: str | None = None) -> dict[int, str]: ...


def brute_force_dict_search(targetstr: str, datadict: dict[int, str]) -> None: ...
